chessboards: artifacts/chessboard_corners.pkl
intrinsics: artifacts/intrinsic.pkl
output_dir: artifacts/extrinsic.pkl

board:
  cols: 6
  rows: 4
  square_size: 38.2857 # unit: millimeters

image:
  width: 1920
  height: 1080

cameras:
  - "cam0"
  - "cam1"
  - "cam2"
  - "cam3"
  - "cam4"
  - "cam5"
