output_dir: artifacts/intrinsic.pkl  # also produce a .yaml file for human to read
chessboards: artifacts/chessboard_corners.pkl
log_path: artifacts/intrinsic_calibration.log

drop_first_n_chessboard: 50
max_chessboards: 200

board:
  cols: 8
  rows: 5
  square_size: 79 # unit: millimeters

image:
  width: 1920
  height: 1080