chessboards: artifacts/chessboard_corners.pkl
intrinsics: artifacts/intrinsic.pkl
output_dir: artifacts/extrinsic.pkl
log_path: artifacts/extrinsic_calibration.log

drop_first_n_pairs: 50
max_pairs: 200


board:
  cols: 8
  rows: 5
  square_size: 79 # unit: millimeters

image:
  width: 1920
  height: 1080

cameras:
  - "cam0"
  - "cam1"
  - "cam2"
