parallel: True

display: False
max_display: 10

save: True
max_save: 9999
save_dir: artifacts

output_dir: artifacts/chessboard_corners.pkl  # also produce a .yaml file for human to read

board:
  cols: 6
  rows: 4

images:
  cam0:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_000050215012/2025-06-11_14-35-19
    offset: 0
  cam1:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_000619514412/2025-06-11_14-35-19
    offset: 0
  cam2:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_000623301312/2025-05-26_14-30-12
    offset: 0
  cam3:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_000756301312/2025-05-26_14-30-12
    offset: 0
  cam4:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_000757214012/2025-06-11_14-34-54
    offset: 0
  cam5:
    path: C:/Users/yuboh/GitHub/data/extracted_frames/k4a_001512595012/2025-06-11_14-34-54
    offset: 0
