path: artifacts/3d_skeletons.pkl

save: true
save_path: artifacts/skeleton_3d

background_color: [0.9, 0.9, 0.9]

point:
  color: [0.0, 1.0, 0.0]   # Green color
  size: 6.0                # Size in pixels

line:
  color: [0.0, 0.0, 0.0]   # Black color
  width: 6.0               # Width in pixels

halpe_lines:
  - [0, 1]
  - [1, 2]
  - [2, 3]
  - [3, 7]
  - [0, 4]
  - [4, 5]
  - [5, 6]
  - [6, 8]
  - [9, 10]
  - [11, 12]
  - [11, 13]
  - [13, 15]
  - [15, 17]
  - [15, 19]
  - [15, 21]
  - [12, 14]
  - [14, 16]
  - [16, 18]
  - [16, 20]
  - [16, 22]
  - [11, 23]
  - [12, 24]
  - [23, 25]
  - [24, 26]
  - [27, 28]
  - [28, 29]
  - [29, 30]
  - [31, 32]